language: python
python:
- '3.5'
install:
- pip install ply==3.10
- pip install twine
- pip install -r requirements.txt
- python setup.py sdist bdist_wheel
script:
- twine upload dist/*
env:
  global:
    secure: FJM4sOTiWPGtKxnNvR1iT+S83V0ngrc7D5aqNMIKoAoZgVA8mSecCtlKnLwAsDY/oEIOEm4uC9ykxER6IFUAVTdn0YmPE3BBAU2N6Zz99wqSc2DWfaGNkNut0mUnHyanVY+XXOhOckty9jd2xd7A0wyoAXGWpved9W9mZIm/ylXYg0ftYzNnAwkBvjR2gNt8sWl1vpsAc2q1Lq/XZBppPXLdiosk04D4heClEvqxiSz0hY/y5V6B2YxkDWNQPUsE/tItvDsnG1e9FcxCwZ+zAs99qDeH1Tvjm2P6X0wxrOvOodB134JR5+hKTkQLJg7VQia+Vst8jgmDOesviua6/mGYBv4hyQsIibpCyL810Dx/2bMFoKROTidtm+JEbR2SIkGTP20XATu0cd6gd9UuOlTHBMNwiGcT3tBiRuunCcIC5v4cHMXUEnsJhq8JJyVlRshwuSXWQ6hFTLKF/RQEQYI7V+vbvBK2aHyyO77f3XEWUCzUunboF/FSEXq7YuQjTAnl3kL3YjXZ0ab0/aq5zLpl4P1SVPPp33GIDwVvoWqEGPa+aAeuNu4Swer2FN6Wbh07yv2b92v0UmqXt5UeZbWCCSpGYsM8hD8vxStyuk46QGsoNQbPyB7zZjpyBImhrPfZyfKrr1LagaXSo5kTx4tLyuozReBxGiVBD3eQuVs=
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: "HappyPathway"
  password:
    secure: vnw6U1xPxe0RTEHjdDjIna9o+9nXRefIxjtM23qToNooxSebJncjJkv65mjCfsMqGBdoRrye0oTfuIjf7GzJoJf2/qXQB0X8N+EgI2TXW8LeQa3T66aTZ6+Ep2qrgx/DTMrxOukU6TMS4Zz06B5UReiX8EmSs6cmrV62OQkYQR081nWYUfWSbxnZD9ZmKcJlgwkOEHbzdYdqvXyaas9umCHy5ED5J6Tz8N+wWMCmRMOT+0GmY1kzNHnLySft5jUO52EAbL8S62+MH/hldPiYyH7ExQoqNteLR6IzscwkvRjNyc0DVE7cJmeRmrBi4QAfO8tCzxm1ll1RW9vIJQU6uqYDC/iFCIEXO/LOvL/ziIvdBaa4s97lznJBh2DJfyplLdyQ/Ley68O5m5YlVM7SCzyzOxGdV3XAJc/lQtS0wGev9U3hW8+2/DB/B31+tjdCS9xt/tYdpmQZbByajhpwK676G3V5BaX7wptCprMrHHyzYTxZrMmxSSilA+0TyV2n4tQZxjLYCWDfOsdH+japmgUziORJZPsqEBanLLewZ7JqEKb/0F/N62b6+pPtzqaDqtglzGMGGxTD4MjTjF4l/JJRI2QYwqV1HbuzEyw8NRMA9gDLI8z3kyr8O08fdTNhUwJlCWiGSp3u3V7E8iBzCG6bY/FpoWG1EJ33QCPV56M=
